#!/usr/bin/env bash
# This prints out all the subdomains of a domain
print_out ()
{
	ma=$1
	if [ $# -lt 2 ]
	then
		val=$(dig "www.$ma" | grep -A1 'ANSWER SECTION' | tail -1)
		echo $val | awk '{print "The subdomain www is a " $4 " record and points to " $5}'
		val=$(dig "lb-01.$ma" | grep -A1 'ANSWER SECTION' | tail -1)
		echo $val | awk '{print "The subdomain lb-01 is a " $4 " record and points to " $5}'
		val=$(dig "web-01.$ma" | grep -A1 'ANSWER SECTION' | tail -1)
		echo $val | awk '{print "The subdomain web-01 is a " $4 " record and points to " $5}'
		val=$(dig "web-02.$ma" | grep -A1 'ANSWER SECTION' | tail -1)
		echo $val | awk '{print "The subdomain web-02 is a " $4 " record and points to " $5}'
	else

		val=$(dig "$2.$ma" | grep -A1 'ANSWER SECTION' | tail -1)
		echo $val | awk -v ma="$2" '{print "The subdomain " ma " is a " $4 " record and points to " $5}'
	fi
}
print_out "$@"
