#!/usr/bin/env bash
# THis script instals an nginx server and configures it to return Hello World!

sudo apt-get -y update
sudo apt-get -y install nginx
sudo apt-get -y install nginx-extras
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
