#!/usr/bin/env bash
# THis script instals an nginx server and configures it to return Hello World!

sudo apt-get -y update
sudo apt-get -y install nginx
sudo apt-get -y install nginx-extras
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '/# pass PHP scripts to FastCGI server/i \\tlocation /redirect_me {\n\t\treturn 301 https://wwwgithub.com/2022phyro;\n\t}\n' /etc/nginx/sites-available/default
sudo service nginx restart
