#!/usr/bin/env bash
# THis script instals an nginx server and configures it to return Hello World!

sudo apt-get -y update
sudo apt-get -y install nginx
sudo apt-get -y install nginx-extras
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '/# pass PHP scripts to FastCGI server/i \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/htmml/error404.html
sudo sed -i '/\tlocation \/redirect_me {/i \\terror_page 404 /error404.html;\n\tlocation = /error404.html {\n\t\troot /var/www/html;\n\t\tinternal\n\t}\n' /etc/nginx/sites-available/default
sudo service nginx restart
