#!/usr/bin/env bash
#This debugs this container and allow it listen at 80
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo pkill nginx
sudo service nginx restart
